"""
MetaGen Paper Generator

Main orchestrator for generating publication-quality academic papers.
Combines section generators, figure generators, and bibliography into
a complete LaTeX project ready for compilation.
"""

from __future__ import annotations

from pathlib import Path

from metagen.specs.schema import ModelSpec
from metagen.synth.paper_bibliography import generate_bibliography
from metagen.synth.paper_figures import generate_all_figures
from metagen.synth.paper_sections import (
    generate_abstract,
    generate_appendix,
    generate_conclusion,
    generate_discussion,
    generate_experiments,
    generate_introduction,
    generate_method,
    generate_related_work,
)
from metagen.synth.paper_templates import copy_templates_to
from metagen.utils.io import ensure_dir, write_text


def generate_paper(
    spec: ModelSpec,
    out_dir: Path,
    bench_summary: dict,
    arch_summary: dict,
    seed: int,
) -> None:
    """
    Generate a complete academic paper from a model specification.

    Creates a LaTeX project with:
    - Main document with all sections
    - Custom preamble and style files
    - Publication-quality figures
    - Dynamic bibliography based on spec modalities
    - Makefile for PDF compilation

    Args:
        spec: Model specification.
        out_dir: Output directory for the paper project.
        bench_summary: Benchmark summary with scores.
        arch_summary: Architecture summary with parameters.
        seed: Seed for deterministic generation.

    Example:
        >>> from metagen.specs.loader import load_spec
        >>> spec, _ = load_spec("examples/specs/text_llm_8b.yaml")
        >>> generate_paper(spec, Path("paper/"), bench_summary, arch_summary, 42)
    """
    ensure_dir(out_dir)
    sections_dir = ensure_dir(out_dir / "sections")
    figures_dir = ensure_dir(out_dir / "figures")

    # Copy LaTeX templates (preamble.tex, metagen_academic.sty)
    copy_templates_to(out_dir)

    # Generate all figures
    generate_all_figures(
        spec=spec,
        arch_summary=arch_summary,
        bench_summary=bench_summary,
        figures_dir=figures_dir,
        seed=seed,
    )

    # Generate sections
    _generate_sections(
        spec=spec,
        arch_summary=arch_summary,
        bench_summary=bench_summary,
        sections_dir=sections_dir,
        seed=seed,
    )

    # Generate bibliography
    bibliography = generate_bibliography(spec)
    write_text(out_dir / "bibliography.bib", bibliography)

    # Generate main document
    main_tex = _generate_main_document(spec, arch_summary)
    write_text(out_dir / "main.tex", main_tex)

    # Generate Makefile
    makefile = _generate_makefile()
    write_text(out_dir / "Makefile", makefile)


def _generate_sections(
    spec: ModelSpec,
    arch_summary: dict,
    bench_summary: dict,
    sections_dir: Path,
    seed: int,
) -> None:
    """Generate all paper sections as individual .tex files."""
    sections = {
        "abstract.tex": generate_abstract(spec, arch_summary, bench_summary),
        "introduction.tex": generate_introduction(spec, arch_summary),
        "related_work.tex": generate_related_work(spec),
        "method.tex": generate_method(spec, arch_summary),
        "experiments.tex": generate_experiments(spec, bench_summary, arch_summary),
        "discussion.tex": generate_discussion(spec),
        "conclusion.tex": generate_conclusion(spec, arch_summary),
        "appendix.tex": generate_appendix(spec, arch_summary),
    }

    for filename, content in sections.items():
        write_text(sections_dir / filename, content)


def _generate_main_document(spec: ModelSpec, arch_summary: dict) -> str:
    """Generate the main LaTeX document."""
    title = _generate_title(spec)
    authors = _generate_authors()
    keywords = _generate_keywords(spec)
    date = ""  # Empty for undated preprint style

    return f"""% MetaGen Academic Paper
% Generated by MetaGen - A spec-to-model synthesizer
% Seed: deterministic generation ensures reproducibility

\\input{{preamble}}
\\usepackage{{metagen_academic}}

% ============================================================================
% DOCUMENT METADATA
% ============================================================================

\\title{{{title}}}

\\author{{{authors}}}

\\date{{{date}}}

% PDF metadata
\\hypersetup{{
    pdftitle={{{title}}},
    pdfauthor={{MetaGen Research}},
    pdfsubject={{Neural Architecture Synthesis}},
    pdfkeywords={{{keywords}}}
}}

% ============================================================================
% BEGIN DOCUMENT
% ============================================================================

\\begin{{document}}

\\maketitle

% ============================================================================
% ABSTRACT
% ============================================================================

\\begin{{abstract}}
\\input{{sections/abstract}}
\\end{{abstract}}

% ============================================================================
% MAIN CONTENT
% ============================================================================

\\section{{Introduction}}
\\label{{sec:introduction}}
\\input{{sections/introduction}}

\\section{{Related Work}}
\\label{{sec:related_work}}
\\input{{sections/related_work}}

\\section{{Method}}
\\label{{sec:method}}
\\input{{sections/method}}

\\section{{Experiments}}
\\label{{sec:experiments}}
\\input{{sections/experiments}}

\\section{{Discussion}}
\\label{{sec:discussion}}
\\input{{sections/discussion}}

\\section{{Conclusion}}
\\label{{sec:conclusion}}
\\input{{sections/conclusion}}

% ============================================================================
% ACKNOWLEDGMENTS
% ============================================================================

\\section*{{Acknowledgments}}

This work was generated by \\metagen{{}}, a spec-to-model synthesizer that
produces complete AI model release artifacts from high-level specifications.
We thank the reviewers for their constructive skepticism and the compute
infrastructure for its optimistic availability assumptions. No actual models
were harmed in the production of this paper, though several parameter budgets
were exceeded under best-effort conditions.

% ============================================================================
% BIBLIOGRAPHY
% ============================================================================

\\bibliography{{bibliography}}

% ============================================================================
% APPENDIX
% ============================================================================

\\clearpage
\\appendix
\\appendixsetup

\\section{{Appendix}}
\\label{{sec:appendix}}
\\input{{sections/appendix}}

\\end{{document}}
"""


def _generate_title(spec: ModelSpec) -> str:
    """Generate a paper title based on the spec."""
    # Get unique modalities from inputs and outputs
    all_modalities = list(dict.fromkeys(spec.modality.inputs + spec.modality.outputs))

    if len(all_modalities) == 1:
        modality_str = all_modalities[0].capitalize()
    elif len(all_modalities) == 2:
        modality_str = f"{all_modalities[0].capitalize()}-{all_modalities[1].capitalize()}"
    else:
        modality_str = "Multimodal"

    family = spec.architecture.family.capitalize()

    return f"MetaGen: Synthesizing {modality_str} {family} Architectures via Latent Space Diffusion"


def _generate_authors() -> str:
    """Generate the author list."""
    return (
        "MetaGen Research\\affilimark{1} \\and "
        "Department of Computational Ambition\\affilimark{2}\n\n"
        "\\affiliation{1}{Institute for Spec-Driven Development}\n"
        "\\affiliation{2}{Center for Optimistic Parameter Estimation}"
    )


def _generate_keywords(spec: ModelSpec) -> str:
    """Generate keywords based on the spec."""
    keywords = [
        "neural architecture synthesis",
        "spec-to-model",
        spec.architecture.family.lower(),
    ]

    # Add unique modalities
    all_modalities = list(dict.fromkeys(spec.modality.inputs + spec.modality.outputs))
    for modality in all_modalities:
        keywords.append(modality.lower())

    # Add training objectives
    if spec.training.objective:
        for obj in spec.training.objective:
            keywords.append(obj.lower())

    return ", ".join(keywords)


def _generate_makefile() -> str:
    """Generate the paper build Makefile."""
    return """# MetaGen Paper Build
# Requires: pdflatex, bibtex (or latexmk)

TEX = main.tex
PDF = main.pdf

.PHONY: pdf clean view

pdf: $(PDF)

$(PDF): $(TEX) sections/*.tex figures/*.pdf bibliography.bib
\t@echo "Building paper..."
\t@latexmk -pdf -interaction=nonstopmode -halt-on-error $(TEX) 2>/dev/null || \\
\t(pdflatex -interaction=nonstopmode -halt-on-error $(TEX) && \\
\tbibtex main && \\
\tpdflatex -interaction=nonstopmode -halt-on-error $(TEX) && \\
\tpdflatex -interaction=nonstopmode -halt-on-error $(TEX))
\t@echo "Paper built: $(PDF)"

clean:
\t@latexmk -C 2>/dev/null || true
\t@rm -f *.aux *.log *.out *.bbl *.blg *.toc *.lof *.lot *.fls *.fdb_latexmk
\t@rm -f sections/*.aux
\t@echo "Cleaned build artifacts"

view: $(PDF)
\t@open $(PDF) 2>/dev/null || xdg-open $(PDF) 2>/dev/null || echo "Open $(PDF) manually"

# Quick build (single pass, no bibliography)
quick:
\tpdflatex -interaction=nonstopmode $(TEX)
"""


def _latex_escape(text: str) -> str:
    """Escape special LaTeX characters in text."""
    replacements = {
        "\\": "\\textbackslash{}",
        "&": "\\&",
        "%": "\\%",
        "$": "\\$",
        "#": "\\#",
        "_": "\\_",
        "{": "\\{",
        "}": "\\}",
        "~": "\\textasciitilde{}",
        "^": "\\textasciicircum{}",
    }
    for key, val in replacements.items():
        text = text.replace(key, val)
    return text
